sap.ui.define(["dynamic/Table/js/Base", "sap/m/Toolbar", "sap/ui/core/Title", "sap/ui/layout/form/SimpleForm", "sap/m/Text", "sap/m/Label"],
    function(Base, Toolbar, Title, SimpleForm, Text, Label) {
        "use strict";
        return Base.extend("dynamic.Table.js.Control", {

            /**
             * User-interface class for generating a responsive table which gets
             * inserted into the page dynamically, and whose columns are updated
             * dynamically by a set of configurations provided by a JSON model
             *
             * @class      DynamicTable.js.Control
             * @subject    DynamicTable.js.Control
             * @augments   DynamicTable.js.Base
             * @param      {String}  sId     Unique ID generated by the
             *                               originating controller
             */
            constructor: function(sId) {
                this.sId = sId;
                this.form = new SimpleForm(sId, {
                    editable: true,
                    layout: "ResponsiveGridLayout",
                    labelSpanXL: 3,
                    labelSpanL: 3,
                    labelSpanM: 3,
                    labelSpanS: 3,
                    adjustLabelSpan: false,
                    emptySpanXL: 0,
                    emptySpanL: 0,
                    emptySpanM: 0,
                    emptySpanS: 0,
                    columnsXL: 2,
                    columnsL: 2,
                    columnsM: 2,
                    columnsS: 2
                });
            },

            /**
             * Sets the configuration settings as a property in the model
             *
             * @method     setConfiguration
             * @memberof   DynamicTable.js.Control
             * @param      {Object}  oConfig  The configuration settings
             */
            setConfiguration: function(oConfig) {
                var oModel = this.getEmptyModel();
                oModel.setSizeLimit(250000);  
                oModel.setProperty("/columns", oConfig.columns);
                this.form.setModel(oModel);
                this.getContent(oConfig);
            },

            getContent: function(oConfig) {
                for (var i = 0; i < oConfig.formContainers.length; i++) {
                    if(oConfig.formContainers[i].title) {
                        this.form.addContent(oConfig.formContainers[i].title);
                    }
                    if(oConfig.formContainers[i].label) {
                        this.form.addContent(oConfig.formContainers[i].label);
                    }
                    if(oConfig.formContainers[i].control) {
                        this.form.addContent(oConfig.formContainers[i].control);
                    }
                }
            },

            /**
             * Returns the user-interface control for the table object
             *
             * @method     getControl
             * @memberof   DynamicTable.js.Control
             * @return     {Object}  sap.m.Table
             * @public
             */
            getControl: function() {
                return (this.form);
            }

        })
    });